# curl -s "https://adventofcode.com/2025/day/1/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day01.txt
# curl -s "https://adventofcode.com/2025/day/2/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day02.txt
# curl -s "https://adventofcode.com/2025/day/3/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day03.txt
curl -s "https://adventofcode.com/2025/day/4/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day04.txt
curl -s "https://adventofcode.com/2025/day/5/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day05.txt
# curl -s "https://adventofcode.com/2025/day/6/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day06.txt
# curl -s "https://adventofcode.com/2025/day/7/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day07.txt
# curl -s "https://adventofcode.com/2025/day/8/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day08.txt
# curl -s "https://adventofcode.com/2025/day/9/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day09.txt
# curl -s "https://adventofcode.com/2025/day/10/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day10.txt
# curl -s "https://adventofcode.com/2025/day/11/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day11.txt
# curl -s "https://adventofcode.com/2025/day/12/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day12.txt
# curl -s "https://adventofcode.com/2025/day/13/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day13.txt
# curl -s "https://adventofcode.com/2025/day/14/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day14.txt
# curl -s "https://adventofcode.com/2025/day/15/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day15.txt
# curl -s "https://adventofcode.com/2025/day/16/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day16.txt
# curl -s "https://adventofcode.com/2025/day/17/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day17.txt
# curl -s "https://adventofcode.com/2025/day/18/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day18.txt
# curl -s "https://adventofcode.com/2025/day/19/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day19.txt
# curl -s "https://adventofcode.com/2025/day/20/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day20.txt
# curl -s "https://adventofcode.com/2025/day/21/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day21.txt
# curl -s "https://adventofcode.com/2025/day/22/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day22.txt
# curl -s "https://adventofcode.com/2025/day/23/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day23.txt
# curl -s "https://adventofcode.com/2025/day/24/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day24.txt
# curl -s "https://adventofcode.com/2025/day/25/input" --cookie "session=$AOC_SESSION" --output ./2025/input/day25.txt
